name: build 

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Integration failure notifications
        uses: ./
        env:
            LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK}} 
            ACTOR: ${{github.actor}}
        with:
          state: "hello world"
   


